export const queryKeys = {
  auth_session: "auth-session",
  subscription: "subscription",
  membership_plans: "membership-plans",
  applications: "applications",
  users: "users",
  webinars: "webinars",
  podcasts: "podcasts",
  research: "research",
  leads: "leads",
  webinar_registrations: "webinar-registrations",
  qna: "qna",
  staff_section_edit_access: "staff-section-edit-access",
  admin_staff_section_edit_access: "admin-staff-section-edit-access",
};
